spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/recipe_app}
    username: ${SPRING_DATASOURCE_USERNAME:recipe_user}
    password: ${SPRING_DATASOURCE_PASSWORD:recipe_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    com.zaxxer.hikari: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: env

server:
  port: ${SERVER_PORT:8080}


# App-specific config
app:
  todoist:
    client-id: ${TODOIST_CLIENT_ID:}
    client-secret: ${TODOIST_CLIENT_SECRET:}