spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/recipe_app
    username: recipe_user
    password: recipe_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080