version: '3.8'
services:
  postgres:
    image: 'postgres:17.6-alpine3.21'
    environment:
      POSTGRES_DB: recipe_app
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: .
    container_name: recipe-app-backend
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: